name: test
on:
  workflow_dispatch:
jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "${GITHUB_REF_NAME}"
      - uses: actions/checkout@v3
        with:
          ref: ${GITHUB_REF_NAME}
