name: test
on:
  workflow_dispatch:
jobs:
  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "${{ github.ref_name }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
